//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1_Files.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E1_Files.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete this {0}? This action may be irreversible.
        /// </summary>
        internal static string CONFIRMDELETE_MSG {
            get {
                return ResourceManager.GetString("CONFIRMDELETE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure?.
        /// </summary>
        internal static string CONFIRMDELETE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRMDELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a directory.
        /// </summary>
        internal static string DIR_SNIPPET {
            get {
                return ResourceManager.GetString("DIR_SNIPPET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The directory you are trying to access has is restricted..
        /// </summary>
        internal static string ERR_ACCESS_MSG {
            get {
                return ResourceManager.GetString("ERR_ACCESS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restricted acess.
        /// </summary>
        internal static string ERR_ACCESS_TITLE {
            get {
                return ResourceManager.GetString("ERR_ACCESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s nothing selected on this list to delete!.
        /// </summary>
        internal static string ERR_DELETENOSELECTION_MSG {
            get {
                return ResourceManager.GetString("ERR_DELETENOSELECTION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No selection.
        /// </summary>
        internal static string ERR_DELETENOSELECTION_TITLE {
            get {
                return ResourceManager.GetString("ERR_DELETENOSELECTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There has been an error trying to delete the file
        ///Error type: {0}.
        /// </summary>
        internal static string ERR_DELETING_MSG {
            get {
                return ResourceManager.GetString("ERR_DELETING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting file.
        /// </summary>
        internal static string ERR_DELETING_TITLE {
            get {
                return ResourceManager.GetString("ERR_DELETING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s no directory selected to go to!.
        /// </summary>
        internal static string ERR_GOTONONE_MSG {
            get {
                return ResourceManager.GetString("ERR_GOTONONE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No directory selected!.
        /// </summary>
        internal static string ERR_GOTONONE_TITLE {
            get {
                return ResourceManager.GetString("ERR_GOTONONE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s illegal characters in this path! Be careful with characters like .
        /// </summary>
        internal static string ERR_ILLEGALPATH_MSG {
            get {
                return ResourceManager.GetString("ERR_ILLEGALPATH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Illegal path!.
        /// </summary>
        internal static string ERR_ILLEGALPATH_TITLE {
            get {
                return ResourceManager.GetString("ERR_ILLEGALPATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t go nowhere! Please specify a path to go to!.
        /// </summary>
        internal static string ERR_NOPATH_MSG {
            get {
                return ResourceManager.GetString("ERR_NOPATH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ooops, no path!.
        /// </summary>
        internal static string ERR_NOPATH_TITLE {
            get {
                return ResourceManager.GetString("ERR_NOPATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There has been an error trying to access the file
        ///Error type: {0}.
        /// </summary>
        internal static string ERR_OPENFILE_MSG {
            get {
                return ResourceManager.GetString("ERR_OPENFILE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error opening file.
        /// </summary>
        internal static string ERR_OPENFILE_TITLE {
            get {
                return ResourceManager.GetString("ERR_OPENFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s no file selected to view!.
        /// </summary>
        internal static string ERR_OPENNONE_MSG {
            get {
                return ResourceManager.GetString("ERR_OPENNONE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file selected!.
        /// </summary>
        internal static string ERR_OPENNONE_TITLE {
            get {
                return ResourceManager.GetString("ERR_OPENNONE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error trying to change directory: .
        /// </summary>
        internal static string ERR_PATH_MSG {
            get {
                return ResourceManager.GetString("ERR_PATH_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t change directory.
        /// </summary>
        internal static string ERR_PATH_TITLE {
            get {
                return ResourceManager.GetString("ERR_PATH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a file.
        /// </summary>
        internal static string FILE_SNIPPET {
            get {
                return ResourceManager.GetString("FILE_SNIPPET", resourceCulture);
            }
        }
    }
}
